use miette::{IntoDiagnostic, Result, WrapErr};
use std::io::Write;
use std::process::{Command, Stdio};

#[derive(clap::Args)]
pub struct CompletionArgs {
    /// The shell to generate completions for (bash, zsh, fish)
    #[arg(value_name = "SHELL")]
    pub shell: String,
}

pub async fn run(args: CompletionArgs) -> Result<()> {
    // Command name from the active embedder (standalone aube → "aube").
    let name = aube_util::embedder().name;
    let usage_cmd = format!("{name} usage");
    let output = Command::new("usage")
        .args([
            "g",
            "completion",
            &args.shell,
            name,
            "--usage-cmd",
            &usage_cmd,
            "--cache-key",
            env!("CARGO_PKG_VERSION"),
        ])
        .output()
        .into_diagnostic()
        .wrap_err("failed to invoke `usage`; install it from https://usage.jdx.dev")?;
    ensure_success(&args.shell, &output)?;

    let mut aubr = Command::new("usage")
        .args(["g", "completion", &args.shell, "aubr", "-f", "-"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .into_diagnostic()
        .wrap_err("failed to invoke `usage`; install it from https://usage.jdx.dev")?;
    let spec = aubr_usage_spec();
    let mut stdin = aubr.stdin.take().ok_or_else(|| {
        miette::miette!(
            code = aube_codes::errors::ERR_AUBE_COMPLETION_FAILED,
            "failed to open stdin for `usage g completion {}`",
            args.shell
        )
    })?;
    stdin
        .write_all(spec.as_bytes())
        .into_diagnostic()
        .wrap_err("failed to send the aubr usage spec to `usage`")?;
    drop(stdin);
    let aubr = aubr
        .wait_with_output()
        .into_diagnostic()
        .wrap_err("failed to wait for `usage` to generate aubr completions")?;
    ensure_success(&args.shell, &aubr)?;

    let mut stdout = std::io::stdout();
    stdout
        .write_all(&output.stdout)
        .into_diagnostic()
        .wrap_err("failed to write completions to stdout")?;
    stdout
        .write_all(&aubr.stdout)
        .into_diagnostic()
        .wrap_err("failed to write aubr completions to stdout")?;
    Ok(())
}

fn ensure_success(shell: &str, output: &std::process::Output) -> Result<()> {
    if output.status.success() {
        return Ok(());
    }
    let stderr = String::from_utf8_lossy(&output.stderr);
    Err(miette::miette!(
        code = aube_codes::errors::ERR_AUBE_COMPLETION_FAILED,
        "`usage g completion {shell}` failed: {}",
        stderr.trim()
    ))
}

fn aubr_usage_spec() -> String {
    let mut cmd = crate::command();
    let mut spec = clap_usage::spec(&mut cmd, aube_util::prog());
    let root_flags = spec
        .cmd
        .flags
        .iter()
        .filter(|flag| flag.global)
        .cloned()
        .collect::<Vec<_>>();
    // WHY: `run` is a compile-time member of `Cli`; if it disappeared this
    // completion generator would be invalid and its focused test would fail.
    let mut run = spec
        .cmd
        .subcommands
        .shift_remove("run")
        .expect("aube command must contain run");
    run.flags.splice(0..0, root_flags);
    run.name = "aubr".to_string();
    run.full_cmd = vec!["aubr".to_string()];
    run.aliases.clear();
    run.hidden_aliases.clear();
    run.usage = run.usage.replacen(&aube_util::cmd("run"), "aubr", 1);

    spec.name = "aubr".to_string();
    spec.bin = "aubr".to_string();
    spec.usage = run.usage.clone();
    spec.about = run.help.clone();
    spec.about_long = run.help_long.clone();
    spec.cmd = run;

    format!(
        "// @generated by aube for the aubr multicall surface\n{spec}\n{}",
        include_str!("../../assets/extra.usage.kdl").replace("{run}", "aubr")
    )
}

#[cfg(test)]
mod tests {
    use super::aubr_usage_spec;

    #[test]
    fn aubr_spec_roots_run_arguments_and_dynamic_completion() {
        let spec = aubr_usage_spec();
        assert!(spec.contains("name aubr\nbin aubr"));
        assert!(spec.contains("arg \"[SCRIPT]\""));
        assert!(spec.contains("flag --no-install"));
        assert!(spec.contains("flag \"-C --dir --cd --prefix\""));
        assert!(spec.contains("complete \"script\" run=\"aubr --complete\""));
        assert!(!spec.contains("\ncmd install "));
    }
}
